- name: Delete an existing VPC
  hosts: localhost
  connection: local
  tasks:
    - name: Delete an existing ec2
      amazon.aws.ec2_instance:
        instance_ids: i-0df6f51477ca34395 # replace with correct ids here and below
        state: absent
        region: us-east-1

    - name: Delete an existing security group
      amazon.aws.ec2_group:
        group_id: sg-03014875e7bba92ce
        state: absent
        region: us-east-1

    - name: Delete an existing internet gateway
      amazon.aws.ec2_vpc_igw:
        internet_gateway_id: igw-00839b0f12a69c084
        vpc_id: vpc-023260ca3dae21188
        state: absent
        region: us-east-1

    - name: Delete an existing route table
      amazon.aws.ec2_vpc_route_table:
        route_table_id: rtb-0d0c7a7fef5fbd3c2
        vpc_id: vpc-023260ca3dae21188
        state: absent
        region: us-east-1

    - name: Delete an existing subnet
      amazon.aws.ec2_vpc_subnet:
        vpc_id: vpc-023260ca3dae21188
        cidr: 10.10.0.0/24
        state: absent
        region: us-east-1

    - name: Delete an existing VPC
      amazon.aws.ec2_vpc_net:
        vpc_id: vpc-023260ca3dae21188
        state: absent
        region: us-east-1 